/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.kunalmalik_fees_management_system;


import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getInt;





/**
 *
 * @author MY LENOVO
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        
        Container c = getContentPane();
        c.setBackground(new Color(0,153,153));
    }
    
    int id=0;
  int getId() throws ClassNotFoundException, SQLException
{
    ResultSet rs=null;
    Class.forName("com.mysql.cj.jdbc.Driver");
    String url="jdbc:mysql://localhost:3306/codingseekho fees?zeroDateTimeBehavior=CONVERT_TO_NULL";
    Connection con=DriverManager.getConnection(url,"root","kunalmalik@123");
    String sql="select max(id) from signup";
    Statement st=con.createStatement();
    rs=st.executeQuery(sql);
    while(rs.next())
    {
          id=getInt(1);
           id++;
    }
  return id;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextField4 = new javax.swing.JTextField();
        TextField1 = new javax.swing.JTextField();
        TextField3 = new javax.swing.JTextField();
        TextField2 = new javax.swing.JTextField();
        PasswordField2 = new javax.swing.JPasswordField();
        PasswordField1 = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        btnsignup = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lebelconfirmpassworderror = new javax.swing.JLabel();
        labelcontactnumber = new javax.swing.JLabel();
        labelpassworderror = new javax.swing.JLabel();
        txtdob = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:///C:/Users/MY%20LENOVO/Documents/NetBeansProjects/Kunalmalik_fees_management_system/src/main/java/com/mycompany/kunalmalik_fees_management_system/images/new-user.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel1.setText("Sign Up");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 210, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Last name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Contact number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Username");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 70));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, 70));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Confirm Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, 70));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("First name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 70));

        TextField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextField4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField4KeyTyped(evt);
            }
        });
        getContentPane().add(TextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 160, 30));

        TextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(TextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 160, 30));

        TextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(TextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 160, -1));

        TextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(TextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 160, 30));

        PasswordField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordField2ActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 160, 30));

        PasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordField1ActionPerformed(evt);
            }
        });
        PasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswordField1KeyTyped(evt);
            }
        });
        getContentPane().add(PasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 160, 30));

        btnlogin.setBackground(new java.awt.Color(0, 255, 0));
        btnlogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\MY LENOVO\\Documents\\my icons\\login.png")); // NOI18N
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, 40));

        btnsignup.setBackground(new java.awt.Color(0, 255, 51));
        btnsignup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsignup.setIcon(new javax.swing.ImageIcon("C:\\Users\\MY LENOVO\\Documents\\my icons\\signup.png")); // NOI18N
        btnsignup.setText("Sign Up");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, 40));

        btnclear.setBackground(new java.awt.Color(0, 255, 0));
        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon("C:\\Users\\MY LENOVO\\Documents\\my icons\\delete.png")); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("DOB");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 90, 30));

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 170, -1));

        lebelconfirmpassworderror.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lebelconfirmpassworderror.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lebelconfirmpassworderror, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 140, 20));

        labelcontactnumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelcontactnumber.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(labelcontactnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 140, 20));

        labelpassworderror.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelpassworderror.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(labelpassworderror, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 140, 20));

        txtdob.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 342, 160, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField1ActionPerformed

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
// validation();
if(validation())
{
insertData();
}
else
{
JOptionPane.showMessageDialog(this,"Validation Issue");
}
    }//GEN-LAST:event_btnsignupActionPerformed

    private void PasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordField2ActionPerformed

    private void PasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordField1ActionPerformed

    private void PasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordField1KeyPressed
        // TODO add your handling code here:
passwordCheck();
    }//GEN-LAST:event_PasswordField1KeyPressed

    private void PasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordField1KeyReleased
        // TODO add your handling code here:
        passwordCheck();
    }//GEN-LAST:event_PasswordField1KeyReleased

    private void PasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordField1KeyTyped
        // TODO add your handling code here:
        passwordCheck();
    }//GEN-LAST:event_PasswordField1KeyTyped

    private void TextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField4KeyPressed
        // TODO add your handling code here:
        mobileCheck();
    }//GEN-LAST:event_TextField4KeyPressed

    private void TextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField4KeyReleased
      mobileCheck();  // TODO add your handling code here:
    }//GEN-LAST:event_TextField4KeyReleased

    private void TextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField4KeyTyped
mobileCheck();        // TODO add your handling code here:
    }//GEN-LAST:event_TextField4KeyTyped

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
Login l1=new Login();
l1.setVisible(true);
this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
                    TextField1.setText("");
                    TextField2.setText("");
                    TextField3.setText("");
                    PasswordField1.setText("");
                    PasswordField2.setText("");
                  //  txtdob.setDate("");
                   TextField4.setText("");
                    
                    
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed
  String fname, lname, usename, password, conpassword, contnumber;
               Date dob;
               
               
               void insertData()
               {
                   SimpleDateFormat s1=new SimpleDateFormat("yyyy-MM-dd");
                   String dob1=s1.format(dob);
               try
               {
               Class.forName("com.mysql.cj.jdbc.Driver");
               String url="jdbc:mysql://localhost:3306/codingseekho fees?zeroDateTimeBehavior=CONVERT_TO_NULL";
               Connection con=DriverManager.getConnection(url,"root","kunalmalik@123");
               
               String sql="insert into signup values(?,?,?,?,?,?,?)";
               PreparedStatement st=con.prepareStatement(sql);
               
               st.setInt(1,getId());
               st.setString(2,fname);
               st.setString(3,lname);
               st.setString(4,usename);
               st.setString(5,password);  
               st.setString(6,dob1);
               st.setString(7,contnumber);
                 int i=st.executeUpdate();
                 if(i>0)
                 {
                 JOptionPane.showMessageDialog(this,"Record inserted successfully");
                 }
                 else
                 {
                  JOptionPane.showMessageDialog(this,"Record not inserted successfully");
                 }
               }
               catch(Exception e)
               {
                     e.printStackTrace();
               }
               }
                       boolean validation()
                       {
                    fname=TextField1.getText();
                    lname=TextField2.getText();
                    usename =TextField3.getText();
                    password =PasswordField1.getText();
                    conpassword =PasswordField2.getText();
                    dob=txtdob.getDate();
                    contnumber=TextField4.getText();
                   
                    if(fname.equals(""))
                    {
                    JOptionPane.showMessageDialog(this,"Please enter first name:...");
                    return false;
                    }
                      if(lname.equals(""))
                    {
                    JOptionPane.showMessageDialog(this,"Please enter last name:...");
                    return false;
                    }
                        if(usename.equals(""))
                    {
                    JOptionPane.showMessageDialog(this,"Please enter user name:...");
                    return false;
                    }
                          if(password.equals(""))
                    {
                    JOptionPane.showMessageDialog(this,"Please enter passwword:...");
                    return false;
                    }
                            if(conpassword.equals(""))
                    {
                    JOptionPane.showMessageDialog(this,"Please enter confirmpassword:...");
                    return false;
                    }
                              if(dob.equals("null"))
                   {
                    JOptionPane.showMessageDialog(this,"Please enter date of birth:...");
                    return false;
                   }
                                if(contnumber.equals(""))
                    {
                    JOptionPane.showMessageDialog(this,"Please enter contact name:...");
                    return false;
                    }
                                return true;
                       }
                       
                  void passwordCheck()
                       {
                      password=PasswordField1.getText();
                      if(password.length()>=8)
                      {
                         labelpassworderror.setText("");
                      }
                      else
                      {
                      labelpassworderror.setText("Enter 8 digit paassword");
                      }
                       }
                  
                  void mobileCheck()
                  {
                  contnumber=TextField4.getText();
                  if(contnumber.length()==10)
                  {
                      labelcontactnumber.setText("");
                  }
                  else
                  {
                  labelcontactnumber.setText("Enter 10 digits contact number");
                  }
                  }
                       
                       
                       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JPasswordField PasswordField2;
    private javax.swing.JTextField TextField1;
    private javax.swing.JTextField TextField2;
    private javax.swing.JTextField TextField3;
    private javax.swing.JTextField TextField4;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnsignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelcontactnumber;
    private javax.swing.JLabel labelpassworderror;
    private javax.swing.JLabel lebelconfirmpassworderror;
    private com.toedter.calendar.JDateChooser txtdob;
    // End of variables declaration//GEN-END:variables
}
